### ISSUE TITLE
/cb copy <name> coords/current <newName> feature would be dope.

### ISSUE THREAD

**Issue by Stadny** [Geitenijs/CommandBlocks#20]
Basically what the title says.
It would be so dope to just take one commandblock and copy it to currect or coords.

Reason: much easier to copy large amounts of commandblocks and just point your mouse ingame to the block.

Thanks.

**Comment by Stadny** [comment]
Also, bug error after every right click on block:

`[12:40:21] [Server thread/WARN]: [CommandBlocks] Task #2370677 for CommandBlocks v1.3.2 generated an exception
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
	at CommandBlocks-1.3.2.jar/com.geitenijs.commandblocks.Events.lambda$onCommandBlockInteract$0(Events.java:123) ~[CommandBlocks-1.3.2.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-99-1bc02e6]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]`

**Comment by Geitenijs** [comment]
@Stadny you have a malformed blocks.yml file. Make sure NOT to remove ANY entries. If you don't want a certain message to send or command to execute, just use []

Please compare your blocks to the default and adjust accordingly
https://pastebin.com/Yfd4dP8F

**Comment by Stadny** [comment]
Thank you, you a legend!

Also, are you thinking about adding that copy? It would be dope as hell.

Thank you!

**Comment by Geitenijs** [comment]
Shouldn’t be that hard to add. I’ll have a look at it soon

**Comment by Stadny** [comment]
Thank you so much man, it really would be a gamechanger.
Hope it works and will be added as soon as you have time!

**Comment by Stadny** [comment]
Also, I am wondering, is there any possibility of you maybe making custom RPG travel plugin?
Something like this: https://www.spigotmc.org/resources/horsetravel-an-rpg-fast-travel.56360/

You know, you specify path and the horse spawns, gets you at the end and despawns.

Thanks.

**Comment by Geitenijs** [comment]
Well I don’t have time to do so unfortunately, but I think you can get this to work with TrainCarts and TC-Coasters. Set up an invisible rail and change the minecart to whatever entity you want. You can then use train spawners, stations, speed signs, ejectors, destoyers and whatnot.

**Comment by Stadny** [comment]
Oh! Thank you, this looks like its gonna work!
Thank you at least for trying to add the copy function, looking forward to it!

**Comment by Geitenijs** [comment]
Yeah I’m sure that’s gonna work out! People have made entire themeparks with those plugins. Super advanced stuff.

will keep you posted about the copy feature. Have a nice day

**Comment by Stadny** [comment]
Hello, any update on the copy function?

**Comment by Geitenijs** [comment]
Yeah I've just published v1.4.0! Just put the name of the CommandBlock you'd like to copy at the end of the /cb create command

**Comment by Stadny** [comment]
You a frickin legend man! I have read through the changelog and you also implemented feature to remove unneeded options and it wont have the bug in console!

Thank you so much again!

**Comment by Geitenijs** [comment]
You're welcome!
