### ISSUE TITLE
Exception on block interact.

### ISSUE THREAD

**Issue by diontimmer** [Geitenijs/CommandBlocks#8]
**Describe the bug**
Exception prints out in console after interacting with a CommandBlocks block in 1.16.3.

**To Reproduce**
1. Create CommandBlock
2. Right-Click CommandBlock

**Expected behavior**
Clean performance of the command without console spam.
```
[09:45:35 WARN]: [CommandBlocks] Task #62830 for CommandBlocks v1.2.5 generated an exception
java.lang.NullPointerException: null
        at com.geitenijs.commandblocks.Events.lambda$onCommandBlockInteract$0(Events.java:122) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-204]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-204]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-204]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Running paper 1.16.3

**Comment by Geitenijs** [comment]
Can't seem to reproduce it... If it's still an issue feel free to reopen
